"""Added profile description to Users and created at for TicketNote

Revision ID: 0dbbe5e00af7
Revises: 0531b9950625
Create Date: 2026-01-22 22:51:08.089031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbbe5e00af7'
down_revision = '0531b9950625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticketnote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile')

    with op.batch_alter_table('ticketnote', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
